# general settings
name: NAFNetSR-S_x4_DIV2K_GT96_600k_B4G8_valDIV2K
model_type: SRModel
scale: 4
num_gpu: 8
manual_seed: 36

datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /root/datasets/NTIRE2023/DIV2K/DIV2K_train_HR
    dataroot_lq: /root/datasets/NTIRE2023/DIV2K/DIV2K_train_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /root/datasets/NTIRE2023/DIV2K/DIV2K_valid_HR
    dataroot_lq: /root/datasets/NTIRE2023/DIV2K/DIV2K_valid_LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

network_g:
  type: NAFNetSR
  up_scale: 4
  width: 64
  num_blks: 32
  img_channel: 3
  drop_path_rate: 0.1
  drop_out_rate: 0.

  #NAFNetSR-S
  #width: 64
  #num_blks: 32
  #drop_path_rate: 0.1
  #train_size: [1, 1, 48, 48]
  #drop_out_rate: 0.

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [150000, 150000, 150000, 150000]
    restart_weights: [1, 0.5, 0.5, 0.5]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: NTIRE2023-SRx4
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true